name: Build macOS App

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Install frontend dependencies
        run: bun install
        
      - name: Show Tauri config
        run: cat src-tauri/tauri.conf.json
        
      - name: Debug Tauri workspace
        run: |
          ls -la
          ls -la src-tauri/
          
      - name: Build Tauri app for ${{ matrix.target }}
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_BUILD_DEBUG: true
          TAURI_LOG_LEVEL: debug
        with:
          tauriScript: "bun tauri"
          args: "--verbose --bundles dmg --target ${{ matrix.target }}"
          tagName: ${{ github.ref_type == 'tag' && github.ref_name || 'app-v0.1.0' }}
          releaseName: 'App v0.1.0'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false 